name: Run Python
env: 
  FTP_HOST: ${{ secrets.FTP_HOST }}
  FTP_USER: ${{ secrets.FTP_USER }}
  FTP_PASS: ${{ secrets.FTP_PASS }}

on:
  schedule: 
    - cron: '0/5 7-20 * 9-12,1-7 *'
    - cron: '0/5 21-23,0-6 * 9-12,1-7 *'
  workflow_dispatch:


jobs:

  update:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
    - run: python script.py
